# Generated by Django 3.1.1 on 2020-09-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_auto_20200907_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaultprofile.jpg', null=True, upload_to=''),
        ),
    ]
